# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26d5d1b0d1336a14885c54a84c101311137666b6da2fd2d233362b46324d4793fe2263f8db92002e4729a0635560c7ffd527544ca157f42725c43433088d5c6e

test:
  secret_key_base: 6fc551e70202bd257a30909585c345308ecda56cb9bf38991878939fb6e9c445888116674657d1bd3380dd14bf91d9074cdacf734d0a46d6027bc248d2bb1223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
